ROLE_EVENT_ADMIN = 0
ROLE_EVENT_ORGANIZATION = 1
ROLE_TOURIST = 2

USER_ROLE_CHOICES = (
    (ROLE_EVENT_ADMIN,'Administrador'),
    (ROLE_EVENT_ORGANIZATION,'Organizador de Eventos'),
    (ROLE_TOURIST,'Turista')
)