# Generated by Django 4.0 on 2024-11-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_is_organization_user_is_staff_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Administrador'), (1, 'Organizador de Eventos'), (2, 'Turista')], null=True, verbose_name='Role'),
        ),
    ]
