# Generated by Django 4.0 on 2024-11-08 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSuscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Valido'), (1, 'Invalido'), (2, 'Pendiente')], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='api.user')),
            ],
        ),
    ]
