# Generated by Django 4.0 on 2024-08-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='has_been_greeted',
            field=models.BooleanField(default=False),
        ),
    ]
